In [20]:
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline
import random

In [31]:
w, h = 10, 10
cells = ['X','O','E']
MAX_EMPTY_CELL_PERCENTAGE = 0.2
empty_cells = 0
max_empty_cells = (w * h) * MAX_EMPTY_CELL_PERCENTAGE
# Create a 50-dimensional grid
grid = [['E' for x in range(w)] for y in range(h)]

# Place agents on the grid, leaving 10% of cells empty
for i in range(w):
    for k in range(h):
        cell_value = random.choice(cells)
        grid[i][k] = cell_value
        empty_cells += 1
        if empty_cells >= max_empty_cells:
            cells = ['X','O']

In [32]:
grid_df = pd.DataFrame(grid)
grid_df

   0  1  2  3  4  5  6  7  8  9
0  O  X  X  X  E  X  X  E  E  E
1  E  X  E  O  O  X  O  E  E  O
2  X  X  X  O  X  X  X  X  O  O
3  X  X  X  O  O  X  O  O  O  X
4  O  O  X  O  X  O  X  O  X  X
5  X  O  X  O  X  O  O  O  X  X
6  O  O  O  O  X  X  X  O  X  X
7  O  O  X  O  O  O  O  X  X  X
8  X  X  O  X  X  X  X  O  O  O
9  X  X  X  O  X  O  X  X  O  X

In [38]:
def get_agent_neighbors(x,y):
    for i in range(x-1,x+2):
        for k in range(y-1,y+2):
            print(i, k)

In [36]:
for i in range(w):
    for k in range(h):
        # Ask each agent if they are happy
        print("Agent ", i, ":", k)

Agent  0 : 0
Agent  0 : 1
Agent  0 : 2
Agent  0 : 3
Agent  0 : 4
Agent  0 : 5
Agent  0 : 6
Agent  0 : 7
Agent  0 : 8
Agent  0 : 9
Agent  1 : 0
Agent  1 : 1
Agent  1 : 2
Agent  1 : 3
Agent  1 : 4
Agent  1 : 5
Agent  1 : 6
Agent  1 : 7
Agent  1 : 8
Agent  1 : 9
Agent  2 : 0
Agent  2 : 1
Agent  2 : 2
Agent  2 : 3
Agent  2 : 4
Agent  2 : 5
Agent  2 : 6
Agent  2 : 7
Agent  2 : 8
Agent  2 : 9
Agent  3 : 0
Agent  3 : 1
Agent  3 : 2
Agent  3 : 3
Agent  3 : 4
Agent  3 : 5
Agent  3 : 6
Agent  3 : 7
Agent  3 : 8
Agent  3 : 9
Agent  4 : 0
Agent  4 : 1
Agent  4 : 2
Agent  4 : 3
Agent  4 : 4
Agent  4 : 5
Agent  4 : 6
Agent  4 : 7
Agent  4 : 8
Agent  4 : 9
Agent  5 : 0
Agent  5 : 1
Agent  5 : 2
Agent  5 : 3
Agent  5 : 4
Agent  5 : 5
Agent  5 : 6
Agent  5 : 7
Agent  5 : 8
Agent  5 : 9
Agent  6 : 0
Agent  6 : 1
Agent  6 : 2
Agent  6 : 3
Agent  6 : 4
Agent  6 : 5
Agent  6 : 6
Agent  6 : 7
Agent  6 : 8
Agent  6 : 9
Agent  7 : 0
Agent  7 : 1
Agent  7 : 2
Agent  7 : 3
Agent  7 : 4
Agent  7 : 5
Agent  7 : 6
Agent  7 : 7
Agent  7 : 8
Agent  7 : 9
Agent  8 : 0
Agent  8 : 1
Agent  8 : 2
Agent  8 : 3
Agent  8 : 4
Agent  8 : 5
Agent  8 : 6
Agent  8 : 7
Agent  8 : 8
Agent  8 : 9
Agent  9 : 0
Agent  9 : 1
Agent  9 : 2
Agent  9 : 3
Agent  9 : 4
Agent  9 : 5
Agent  9 : 6
Agent  9 : 7
Agent  9 : 8
Agent  9 : 9